version: "3"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  wordpress:
    image: wordpress:latest
    ports:
      - 5000:80
    volumes:
      - ./core:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_TABLE_PREFIX: wp_

volumes:
  db_data: