version: "3"

services:
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha
    networks:
      - mynetwork

  wordpress:
    image: wordpress
    ports:
      - 5000:80
    volumes:
      - ./public:/var/www/html
      - ./logs:/var/log/apache2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_TABLE_PREFIX: wp_
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

volumes:
  db_data:
