version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpdb
      MYSQL_PASSWORD: wpdb
    networks:
      - wpsite

  #Adminer
  adminer:
    depends_on:
      - db
    image: adminer
    # restart: always
    ports:
      - '5050:8080'
    environment:
      ADMINER_DESIGN: pepa-linha
    networks:
      - wpsite

  #Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '5000:80'
    # restart: always
    volumes: ['./core/:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data:
